### PR TITLE
Removing metrics service implementation

### PR DESCRIPTION
**Pull request by jzonthemtn**
Removing metrics service implementation for #122.

### CODE REVIEW

**Review by RobDickinson — APPROVED** [review]
Looks good :-)

**Comment by RobDickinson** [comment]
The functionality here looks good -- but I think I'm seeing a significant drop in performance with these changes. I ran out of time tonight to gather more details but wanted to give a head's up that this might need more testing before merging.

**Comment by jzonthemtn** [comment]
Interesting. It's probably the `LoggingMetricsService` that uses log4j to output those metrics. I will take a look.

**Comment by jzonthemtn** [comment]
Changed to `NoOpMetricsService`. The other one will go into [Philter](https://github.com/philterd/philter). Performance is more important than metrics, by default.

**Comment by RobDickinson** [comment]
Sounds good!

BTW I think the issue was `logFilterTime()` was calling `LOGGER.debug(...)` where the debug string is expensive to calculate. Changing this to `if (LOGGER.isDebugEnabled()) LOGGER.debug(...)` seemed to resolve the issue.

Agree that `NoOpMetricsService` is a better default -- but you may wanna add that `isDebugEnabled` check on the Philter side?

**Comment by RobDickinson** [comment]
Just tried a few performance tests and it's looking good now, many thanks!

**Pull request merged**
